# Change these first
owner: cr3labs # Your GitHub organization or username, where this repository lives
repo: other-page-status # The name of this repository

sites:
  - name: Other Page App
    url: https://alpha.other.page
  - name: Other Page App API
    url: https://alpha-api.other.page/core/v0/health
  - name: Other Page Portal
    url: https://alpha-portal.other.page
  - name: Other Page Portal API
    url: https://alpha-api.other.page/portal/v1/health
  - name: Other Page Public API
    url: https://alpha-api.other.page/v1/health
  # - name: Other Page Blockchain Service
  #   url: https://alpha-api.other.page/portal/v1/blockchain/health
  # - name: Other Page Indexer Service
  #   url: https://alpha-api.other.page/portal/v1/indexer/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.other.page
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.other.page/icon.png
  themeUrl: https://status.other.page/theme.css
  name: Other Page
  introTitle: Status
  introMessage: 
  navbar:
    # - title: Status
    #   href: /
    # - title: GitHub
    #   href: https://github.com/cr3labs/other-page-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
